@startwbs
skinparam backgroundColor transparent
skinparam ArrowColor #078249
skinparam node {
  BackgroundColor #caebdc
  BorderColor #198754
  FontColor #098724
  FontName Helvetica
}

* QWidget
** QButton
*** QRadioButton
*** QToolButton
*** QCheckBox
*** QPushButton
** QDialog
*** QColorDialog
*** QErrorMessage
*** QFileDialog
**** MyFileOpenDialog
**** MyFileSaveDialog
*** QFontDialog
*** QInputDialog
*** QMessageBox
**** MyCustomMessageBox
** QWindow
*** QMainWindow
*** QToolWindow
@endwbs
