' SPDX-FileCopyrightText: 2026 Gerhard Gappmeier <gerhard.gappmeier@ascolab.com>
' SPDX-License-Identifier: MIT

@starttypesystem

* objtype "BoilerType"
*** var "Pressure [Double]"
*** var "Temperature [Float]"
*** var "Flow [Double] Optional"

** obj "Boiler #1"
*** hasProperty var "Pressure 1500.00"
*** hasProperty var "Temperature 260."
*** hasProperty var "Flow 20.34"

** obj "Boiler #2"
*** hasProperty var "Pressure 1769.00"
*** hasProperty var "Temperature 233."

@endtypesystem
