' SPDX-FileCopyrightText: 2026 Gerhard Gappmeier <gerhard.gappmeier@ascolab.com>
' SPDX-License-Identifier: MIT

@starttypesystem
skinparam nodeMinWidth 180

* objtype "BoilerType"
*** var "Pressure\n[Double]" {#boilertype_pressure}
*** var "Temperature\n[Float]"
*** var "Flow [Double]\nOptional"

** obj "Boiler #1" {#boiler1}
*** hasProperty var "Pressure\n1500.00 kPa" {#boiler1_pressure}
*** hasProperty var "Temperature\n260 °C" {#boiler1_temperature}
*** hasProperty var "Flow\n20.34 m^3/s"

** obj "Boiler #2" {#boiler2}
*** hasProperty var "Pressure\n1769.00 kPa" {#boiler2_pressure}
*** hasProperty var "Temperature\n233 °C" {#boiler2_temperature}

' additional references, automatic anchor point selection
ref AssociatedWith boiler1_pressure - boiler2_pressure
' additional references, manual anchor point selection
ref AssociatedWith [r] boiler1_temperature - boiler2_temperature [r]

@endtypesystem
