# SPDX-FileCopyrightText: 2026 Gerhard Gappmeier <gerhard.gappmeier@ascolab.com>
# SPDX-License-Identifier: GPL-3.0-only

version = 1

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = "2026 Gerhard Gappmeier <gerhard.gappmeier@ascolab.com>"
SPDX-License-Identifier = "GPL-3.0-only"
