' SPDX-FileCopyrightText: 2026 Gerhard Gappmeier <gerhard.gappmeier@ascolab.com>
' SPDX-License-Identifier: MIT

@starttypesystem

* obj "root"
** HasComponent obj "child1"

** HasComponent obj "child2"

** HasComponent obj "child3"

** HasComponent obj "child4"

@endtypesystem
